"""Static schema-v1 lifecycle mirror of shared/telemetry/src/lifecycle.rs."""

from __future__ import annotations

from typing import NamedTuple


BOOLEAN = "boolean"
INTEGER = "integer"
STRING = "string"


class EventDefinition(NamedTuple):
    name: str
    profile_level: int
    profile_name: str
    severity: str
    category: str
    outcome: str
    required_fields: dict[str, str]
    optional_fields: dict[str, str]


def _event(
    name: str,
    profile_level: int,
    severity: str,
    category: str,
    outcome: str,
    required: tuple[tuple[str, str], ...],
    optional: tuple[tuple[str, str], ...] = (),
) -> EventDefinition:
    return EventDefinition(
        name,
        profile_level,
        ("critical", "error", "info", "debug")[profile_level],
        severity,
        category,
        outcome,
        dict(required),
        dict(optional),
    )


# Checked-in static mirror of the append-only Rust definitions.
EVENT_DEFINITIONS = {
    1000: _event(
        "SERVICE_START",
        0,
        "info",
        "health",
        "succeeded",
        (("component", STRING),),
        (("version", STRING), ("pid", INTEGER)),
    ),
    1001: _event(
        "SERVICE_STOP",
        0,
        "info",
        "health",
        "succeeded",
        (("component", STRING), ("reason_class", STRING)),
        (("uptime_ms", INTEGER),),
    ),
    1002: _event(
        "SERVICE_FAILED",
        0,
        "error",
        "health",
        "failed",
        (
            ("component", STRING),
            ("stage", STRING),
            ("reason_class", STRING),
        ),
        (("os_code", INTEGER),),
    ),
    1100: _event(
        "SESSION_AUTH_OK",
        0,
        "info",
        "machine_authentication",
        "succeeded",
        (("auth_method", STRING), ("identity_binding", STRING)),
        (("os_session_id", INTEGER), ("uid", INTEGER)),
    ),
    1101: _event(
        "SESSION_AUTH_FAIL",
        0,
        "warn",
        "machine_authentication",
        "failed",
        (
            ("auth_method", STRING),
            ("stage", STRING),
            ("reason_class", STRING),
        ),
    ),
    1102: _event(
        "SESSION_STREAM_START",
        0,
        "info",
        "streaming",
        "succeeded",
        (
            ("encoder", STRING),
            ("codec", STRING),
            ("chroma", STRING),
            ("width", INTEGER),
            ("height", INTEGER),
        ),
        (("fps", INTEGER), ("display_backend", STRING)),
    ),
    1103: _event(
        "SESSION_END",
        0,
        "info",
        "cleanup",
        "succeeded",
        (("reason_class", STRING), ("duration_ms", INTEGER)),
        (("frames_sent", INTEGER), ("frames_dropped", INTEGER)),
    ),
    1104: _event(
        "SESSION_INTERRUPTED",
        0,
        "warn",
        "reconnect",
        "failed",
        (("stage", STRING), ("reason_class", STRING)),
        (
            ("duration_ms", INTEGER),
            ("frames_sent", INTEGER),
            ("frames_dropped", INTEGER),
        ),
    ),
    1200: _event(
        "DISPLAY_ARMED",
        2,
        "info",
        "health",
        "started",
        (
            ("display_backend", STRING),
            ("policy", STRING),
            ("changed", BOOLEAN),
        ),
        (
            ("width", INTEGER),
            ("height", INTEGER),
            ("os_display_id", STRING),
        ),
    ),
    1201: _event(
        "DISPLAY_RESTORED",
        2,
        "info",
        "cleanup",
        "succeeded",
        (("restore_backend", STRING), ("changed", BOOLEAN)),
        (("width", INTEGER), ("height", INTEGER)),
    ),
    1202: _event(
        "DISPLAY_RESTORE_DEGRADED",
        1,
        "warn",
        "cleanup",
        "succeeded",
        (("restore_backend", STRING), ("reason_class", STRING)),
        (("journal_pending", BOOLEAN),),
    ),
    1203: _event(
        "DISPLAY_RESTORE_FAILED",
        0,
        "error",
        "cleanup",
        "failed",
        (
            ("restore_backend", STRING),
            ("stage", STRING),
            ("reason_class", STRING),
            ("journal_pending", BOOLEAN),
        ),
    ),
    1204: _event(
        "WATCHDOG_RESTORE",
        0,
        "warn",
        "cleanup",
        "succeeded",
        (("restore_backend", STRING), ("reason_class", STRING)),
        (("journal_pending", BOOLEAN),),
    ),
    1300: _event(
        "CP_LOGON_OK",
        0,
        "info",
        "machine_authentication",
        "succeeded",
        (("stage", STRING),),
        (("os_session_id", INTEGER),),
    ),
    1301: _event(
        "CP_LOGON_FAIL",
        0,
        "warn",
        "machine_authentication",
        "failed",
        (("stage", STRING), ("reason_class", STRING)),
    ),
    1400: _event(
        "TLS_CERTIFICATE_ACTIVE",
        0,
        "info",
        "health",
        "succeeded",
        (
            ("component", STRING),
            ("source", STRING),
            ("cert_sha256", STRING),
            ("spki_sha256", STRING),
            ("key_algorithm", STRING),
            ("key_bits", INTEGER),
            ("not_after_epoch_secs", INTEGER),
        ),
    ),
    1401: _event(
        "TLS_CERTIFICATE_EXPIRING",
        1,
        "warn",
        "health",
        "started",
        (
            ("component", STRING),
            ("source", STRING),
            ("cert_sha256", STRING),
            ("spki_sha256", STRING),
            ("key_algorithm", STRING),
            ("key_bits", INTEGER),
            ("not_after_epoch_secs", INTEGER),
            ("days_remaining", INTEGER),
        ),
    ),
    1402: _event(
        "TLS_CERTIFICATE_RELOADED",
        2,
        "info",
        "health",
        "succeeded",
        (
            ("component", STRING),
            ("source", STRING),
            ("cert_sha256", STRING),
            ("spki_sha256", STRING),
            ("key_algorithm", STRING),
            ("key_bits", INTEGER),
            ("not_after_epoch_secs", INTEGER),
        ),
    ),
    1403: _event(
        "TLS_CERTIFICATE_RELOAD_FAILED",
        0,
        "error",
        "health",
        "failed",
        (
            ("component", STRING),
            ("source", STRING),
            ("reason_class", STRING),
        ),
    ),
    1404: _event(
        "TLS_CERTIFICATE_EXPIRED",
        0,
        "error",
        "health",
        "failed",
        (
            ("component", STRING),
            ("source", STRING),
            ("cert_sha256", STRING),
            ("spki_sha256", STRING),
            ("key_algorithm", STRING),
            ("key_bits", INTEGER),
            ("not_after_epoch_secs", INTEGER),
        ),
    ),
    1500: _event(
        "CLIENT_START",
        0,
        "info",
        "health",
        "succeeded",
        (("version", STRING), ("os", STRING), ("arch", STRING)),
    ),
    1501: _event(
        "CLIENT_STOP",
        0,
        "info",
        "health",
        "succeeded",
        (("uptime_ms", INTEGER),),
        (("reason_class", STRING),),
    ),
    1502: _event(
        "CLIENT_CONNECT_ATTEMPT",
        2,
        "info",
        "connection",
        "started",
        (("transport", STRING),),
    ),
    1503: _event(
        "CLIENT_CONNECT_OK",
        0,
        "info",
        "connection",
        "succeeded",
        (("tls_version", STRING),),
        (("rtt_ms", INTEGER),),
    ),
    1504: _event(
        "CLIENT_CONNECT_FAIL",
        0,
        "error",
        "connection",
        "failed",
        (("reason_class", STRING),),
        (("stage", STRING),),
    ),
    1505: _event(
        "CLIENT_SESSION_END",
        0,
        "info",
        "cleanup",
        "succeeded",
        (
            ("duration_ms", INTEGER),
            ("reason_class", STRING),
            ("frames_decoded", INTEGER),
            ("frames_dropped", INTEGER),
        ),
        (
            ("avg_fps", INTEGER),
            ("avg_rtt_ms", INTEGER),
            ("worst_health", STRING),
            ("reconnects", INTEGER),
        ),
    ),
    1506: _event(
        "CLIENT_RECONNECT",
        1,
        "warn",
        "reconnect",
        "started",
        (("attempt", INTEGER), ("gap_ms", INTEGER)),
        (("reason_class", STRING),),
    ),
    1600: _event(
        "HID_DEVICE_ATTACHED",
        2,
        "info",
        "peripheral",
        "succeeded",
        (("vendor_id", INTEGER), ("product_id", INTEGER)),
        (
            ("brand", STRING),
            ("firmware", STRING),
            ("transport", STRING),
        ),
    ),
    1601: _event(
        "HID_DEVICE_DETACHED",
        2,
        "info",
        "peripheral",
        "succeeded",
        (("vendor_id", INTEGER), ("product_id", INTEGER)),
        (
            ("brand", STRING),
            ("firmware", STRING),
            ("transport", STRING),
        ),
    ),
    1602: _event(
        "HID_PASSTHROUGH_START",
        2,
        "info",
        "peripheral",
        "started",
        (
            ("device_id", STRING),
            ("vendor_id", INTEGER),
            ("product_id", INTEGER),
        ),
    ),
    1603: _event(
        "HID_PASSTHROUGH_END",
        2,
        "info",
        "peripheral",
        "succeeded",
        (("device_id", STRING), ("reports_forwarded", INTEGER)),
        (("errors", INTEGER),),
    ),
    1604: _event(
        "HID_PASSTHROUGH_ERROR",
        1,
        "error",
        "peripheral",
        "failed",
        (("device_id", STRING), ("reason_class", STRING)),
    ),
    1700: _event(
        "NETWORK_PATH_ACTIVE",
        2,
        "info",
        "network",
        "succeeded",
        (("interface_kind", STRING), ("scope", STRING)),
        (
            ("link_mbps", INTEGER),
            ("ssid", STRING),
            ("rssi_dbm", INTEGER),
            ("mtu", INTEGER),
        ),
    ),
    1701: _event(
        "NETWORK_PATH_CHANGED",
        2,
        "info",
        "network",
        "succeeded",
        (("old_kind", STRING), ("new_kind", STRING)),
        (
            ("old_mbps", INTEGER),
            ("new_mbps", INTEGER),
            ("reason_class", STRING),
        ),
    ),
    1702: _event(
        "NETWORK_PATH_LOST",
        1,
        "warn",
        "network",
        "failed",
        (("interface_kind", STRING),),
    ),
    1703: _event(
        "NETWORK_PATH_RESTORED",
        1,
        "info",
        "network",
        "succeeded",
        (("interface_kind", STRING), ("gap_ms", INTEGER)),
    ),
    1800: _event(
        "HEALTH_OK",
        0,
        "info",
        "health",
        "succeeded",
        (("previous_state", STRING), ("degraded_duration_ms", INTEGER)),
    ),
    1801: _event(
        "HEALTH_DEGRADED",
        0,
        "warn",
        "health",
        "started",
        (("dominant_cause", STRING), ("value", INTEGER)),
        (("threshold", INTEGER),),
    ),
    1802: _event(
        "HEALTH_CRITICAL",
        0,
        "error",
        "health",
        "failed",
        (("dominant_cause", STRING), ("value", INTEGER)),
        (("threshold", INTEGER),),
    ),
    1803: _event(
        "HEARTBEAT_LOST",
        0,
        "error",
        "health",
        "failed",
        (("missed_intervals", INTEGER),),
    ),
    1804: _event(
        "TELEMETRY_DROPPED",
        0,
        "warn",
        "telemetry",
        "failed",
        (("sink", STRING), ("dropped_count", INTEGER)),
    ),
    1805: _event(
        "EFFECTIVE_PROFILE",
        0,
        "info",
        "telemetry",
        "succeeded",
        (
            ("profile_level", INTEGER),
            ("profile_name", STRING),
            ("profile_source", STRING),
        ),
    ),
    1806: _event(
        "HEALTH_SNAPSHOT",
        0,
        "info",
        "health",
        "succeeded",
        (("overall_state", STRING),),
        (
            ("host_state", STRING),
            ("client_state", STRING),
            ("fps_actual", INTEGER),
            ("fps_target", INTEGER),
            ("rtt_ms", INTEGER),
            ("drop_basis_points", INTEGER),
            ("heartbeat_misses", INTEGER),
        ),
    ),
    1900: _event(
        "PERMISSION_GRANTED",
        2,
        "info",
        "permission",
        "succeeded",
        (("permission", STRING), ("platform", STRING)),
    ),
    1901: _event(
        "PERMISSION_DENIED",
        1,
        "warn",
        "permission",
        "failed",
        (("permission", STRING), ("platform", STRING)),
    ),
    1902: _event(
        "PERMISSION_REVOKED",
        1,
        "warn",
        "permission",
        "failed",
        (("permission", STRING), ("platform", STRING)),
    ),
    1903: _event(
        "PERMISSION_PENDING",
        2,
        "info",
        "permission",
        "started",
        (("permission", STRING), ("platform", STRING)),
    ),
}
